backend:
  name: github
  repo: vivshaw/vivshaw

public_folder: assets
media_folder: content/images

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title, widget: string }
      - { name: blurb, label: Blurb, widget: string, required: false }
      - { name: tags, label: Tags, widget: list }
      - { name: comments, label: Comments?, widget: boolean }
      - { name: toc, label: TOC?, widget: boolean }
      - { name: teaserImage, label: Teaser, widget: image }
      - { name: body, label: Body, widget: markdown }

  - name: work
    label: Work
    folder: content/work
    create: true
    fields:
      - { name: title, label: Title, widget: string }
      - { name: date, label: Date, widget: datetime }
      - { name: blurb, label: Blurb, widget: string }
      - name: image
        label: image
        widget: object
        fields:
          - name: credit
            label: credit
            widget: string
          - name: image
            label: image
            widget: image
      - { name: body, label: Body, widget: markdown }
